### ISSUE TITLE
Color Picker not rendering correctly

### ISSUE THREAD

**Issue by jagaSto** [baianat/verte#10]
**Describe the bug**

Hey guys, I'm having problems with integrating verte into my application. First of all, let me say that it looks like a really lean lib that matches my needs exactly, so good job with that!

Here you see a screenshot of how the color picker currently looks like. Obviously, it doesn't render correctly (missing css?):

![screen shot 2018-09-28 at 09 45 27](https://user-images.githubusercontent.com/20641332/46195008-5d27ae80-c303-11e8-9dbe-f31ecdde84c9.png)

**To Reproduce/ how my code looks like**

my .vue file:
```html
<template>
 <section>
... some other components
    <verte
        :picker="'wheel'"
        :model="'hex'"
        :value="colors">
    </verte>
 </section>
</template>
```
and

```ts
<script lang="ts">
...
import verte from 'verte'
...
export default {
  components: {
     someOtherComponents,
     verte
  }
}
```

Any suggestions on what I'm doing wrong? Is a css importing missing in the docu maybe?

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: chrome
 - Version: 69

**Comment by jagaSto** [comment]
fixed it by adding `import '../node_modules/verte/dist/verte.css'` to my `app.ts`(where i create and mount the app). Makes probably sense to add a hint to the docs about importing the css?

**Comment by Abdelrahman3D** [comment]
Sure, we will add this to docs, thank you for help.
