### ISSUE TITLE
Components opens off-screen causing scroll bars

### ISSUE THREAD

**Issue by wildhart** [baianat/verte#12]
If the component is inserted near the edge of a page, then when it opens it will be partially off the page causing the page to gain horizontal and possibly vertical scroll bars.

**Steps to reproduce**
1. Add the component with `draggable=true` near the edge of the screen, e.g. in a div with `style="float: right"`
2. Open the component
3. The page will get a horizontal scroll bar.

**Expected behavior**
The component should prevent itself openening outside the near the edge of the page (or container?)

It would also be nice (particularly on mobile devices) to have a prop to force the component to open in the center of the page.

Only tested on Linux/Chrome so far.

**Comment by Abdelrahman3D** [comment]
First I want to thank you for your interest in Verte, and your amazing interactive.

Making menu always in the viewport (prevent it from opening outside the edge), requires Verte to do a lot of computation, and add may event listeners for tracking scrolling and resizing, which will lead to increase in the bundle size, and throttling the performance with more event listeners, however you can use a 3rd party like [poopejs](https://popper.js.org) to achieve this specific part.

As a quick fix from my part, we can add an option to set the position of the menu, e.g. top, bottom, left, right, or center which will be (as you mentioned) better for the mobile experience.

**Comment by wildhart** [comment]
Hi @Abdelrahman3D ,

No problem, thank you for your amazing response to my bugs/suggestions and your attention to bundle size which is admirable.

Yes, an option to set the position would be prefect, thank you.

Since you're so responsive to suggestions, I have some more which I will submit as issues...

**Comment by Abdelrahman3D** [comment]
Any suggestions/PRs are welcome, thank you again.
