### ISSUE TITLE
Clicking outside the component to close it does not stop the click event

### ISSUE THREAD

**Issue by wildhart** [baianat/verte#17]
When clicking outside the component to close it, if you accidentally click on a button then that button's click event is fired.

**To Reproduce**
1. Open the component in `display="vertical'` mode with a button somewhere else on the page.
2. Click on the other button.
3. The component closes but the other button's click event also fires.

**Expected behavior**
Clicking outside a dialogue/popup to close it should not cause any other events.

**Comment by Abdelrahman3D** [comment]
We believe it's a better experience not prevent click event bubbling after the picker menu dismiss.

In a real-world example, if we are using a text editor with two buttons, one for making text bold, and the second is a Verte instant which changes text color.
If we select some arbitrary text and change its color using Verte, then want to make it bold, we have to click on the bold button twice, the first click will dismiss Vert's menu then the second will actually fire the bold button.

**Comment by wildhart** [comment]
OK, I suppose you're right, thank you.
