### ISSUE TITLE
Picker "square" invisible color picker in 0.

### ISSUE THREAD

**Issue by auscaster** [baianat/verte#21]
Hey guys,

Really great library, thanks for this!

Just letting you know that under 0.0.9 the color picker UI in "square" mode is invisible. By UI I mean the color gradient picker element. Reverting to 0.0.8 fixes it.

**Comment by enkota** [comment]
I can confirm the same issue with 0.0.12. Reverting back to 0.0.8 fixes it. 

I have noticed if I click the canvas then the range color slider underneath it will eventually appear.

Tested on Chrome/Safari Mac OS mojave - Same issue on both.

![Screenshot 2019-06-13 at 23 50 38](https://user-images.githubusercontent.com/13979799/59472376-14cf0300-8e36-11e9-9867-f1b3797c9143.png)

**Comment by mgochmuradov** [comment]
Any updates on this?

**Comment by mariaines00** [comment]
It looks like this is still a problem and that eddc2cb did not fix it.

Are you planning to release a fix?

🙇‍♀
