### ISSUE TITLE
Unable to choose #ffffff

### ISSUE THREAD

**Issue by auscaster** [baianat/verte#24]
Hey guys

When scrolling hard upper left on the picker canvas it's impossible to select #ffffff, #fefefe is the closest match:

![image](https://user-images.githubusercontent.com/100876/51977367-94f85b80-2487-11e9-8fc1-7d58271537b4.png)

**Comment by Abdelrahman3D** [comment]
I've tried myself, and I can pick `#ffffff`.
![colorpicker](https://user-images.githubusercontent.com/11035467/51981777-20ccb080-24a5-11e9-9bba-ce4935f01098.gif)
