### ISSUE TITLE
Null value instead of #000

### ISSUE THREAD

**Issue by BetimShala** [baianat/verte#25]
I need in some cases to send null value instead of default hex color #000, is that possible?

I tried this way:
 `<verte picker="square" v-model="hexColor" model="hex" :value="null" menuPosition="top">`
...
```
data: function () {
    return { hexColor:null}
  },

```
but I always get #000000 instead of null.

Thanks for any reply or suggestion.

@Abdelrahman3D

**Comment by Abdelrahman3D** [comment]
I am afraid that it not possible at this moment, but you can describe your use case, why exactly you need a color to be null, and maybe we will find a workaround, or add a new feature.

**Comment by KonradDeskiewicz** [comment]
+1 for this option. 
I'm working with system where picker is needed for background color. But `null` means transparent.
Adding alpha slider is too much freedom for users so I'd welcome proper "null" handling.
Maybe as prop: `allow-null` returning null instead of #000?
