### ISSUE TITLE
recentColors prop array doesn't work

### ISSUE THREAD

**Issue by wildhart** [baianat/verte#26]
**Describe the bug**
Passing a `recentColors` prop as an array of colors doesn't set the initial recent color palette.

I'm guessing in [`Verte.vue#L197`](https://github.com/baianat/verte/blob/0f9922dc1d27fafe8a15e84ec6843b9fec095e5b/src/components/Verte.vue#L197):
```js
\\ this:
      return initStore();
\\ needs to be:
      return initStore(Vue, {recentColors: this.recentColors});
```
edit: Added `Vue` as first parameter to `initStore()`.

**Comment by wildhart** [comment]
I guessed wrong!  I didn't see that `initStore()` is also called in `beforeCreate()`.

`this.recentColors` doesn't exist in `beforeCreate()`.  In that case, as well as the above I've fixed it by doing this in [store.js](https://github.com/baianat/verte/blob/0f9922dc1d27fafe8a15e84ec6843b9fec095e5b/src/store.js):
```js
  function initStore (_Vue, opts) {
    if (store) {
	  if (opts && typeof opts.recentColors=='object') store.recentColors = opts.recentColors;
      return store;
    }
```

I see that the `recentColors` and `onRecentColorChange` are intended to be defined with a `Vue.use(...)`.  However, I can't do that because my color picker component is dynamically imported.

**Comment by logaretm** [comment]
The PR #20 implemented the recent colors behavior, as you have said you cannot initialize a different color list during rendering or later on in your app.

Ideally, I think we could introduce a recent color prop which will serve as the source of the colors which will stop the event in the config from firing, it will act as the component is now isolated with its own recent colors, and will emit its own event.

**Comment by wildhart** [comment]
In my opinion PR #20 is a regression.

Before PR #20 , commit https://github.com/baianat/verte/commit/3cd669007ef67d54fa52a43a077a892453cf17bd first introduced the `recentColors` prop in response to issue #15.  That implementation allowed the component to take the recentColors prop as an array any time an instance of the component is rendered.  The developer can choose whether to make that a shared or unique recentColors list between instances.

Then PR #20 broke that behaviour, leaving the **only** way to initialise the recent colors list as `Vue.use()`, which is impossible in some situations where the component is dynamically imported.

The previous behaviour is inline with the [published API](https://baianat.github.io/verte/api.html) which says that 'recentColors' can be an array and makes no mention of `Vue.use()`, and the new behavior is incompatible with the published API.

The two code changes I've shown above allow both uses, either `Vue.use()`, or passing a `recentColors` props as an array (as per the published API).  In both cases the recent colors list is still shared among components.  If you wanted to isolate the recent colors within each instance then that's what the https://github.com/baianat/verte/commit/3cd669007ef67d54fa52a43a077a892453cf17bd did by not using a shared store.  I think the separated list implementation is better because then the developer can choose to use a common recentColors list, or use unique lists for separate components.

**Comment by logaretm** [comment]
My bad, The API was falling behind the actual behavior, I have introduced a new PR #27. Feedback is appreciated!
