### ISSUE TITLE
null value is forced as #000

### ISSUE THREAD

**Issue by KonradDeskiewicz** [baianat/verte#29]
It was discussed before but thread was closed by bot.
Maybe we can go back to that issue.

I'm using Verte in system where background color can be set but when provided as `null` it's treated as transparent. I'd like to use Verte here.
On one hand adding "alpha" slider cause too much confusion within non technical users. 
On the other hand forcing "black" is not a perfect solution as well.

How about prop `allow-null` that will simply return null instead of #000 when no color is provided?

**Comment by auscaster** [comment]
This would be very useful for my use case also.
