### ISSUE TITLE
documentation glitch

### ISSUE THREAD

**Issue by genedronek** [baianat/verte#4]
in the API documentation, in the API table, the model row is duplicated

Fabulous project.  I really like your circular picker.  Why doesn't the rest of the world do it your way?

Oops.  Pilot feebleness.  I am having difficulty getting the *dist* version to work from  vanilla *import verte*.   The white circle will not appear.    Too bad for me, but the picker works well enough w/o the feedback circle for me to keep using verte anyway.   So thanks for verte again.   I do not expect my bug to be very high on your priorities.   Excuse me.  Wow.  nice.  your other projects look quite interesting.

**Comment by logaretm** [comment]
Thanks, will be sure to check both issues out.

**Comment by genedronek** [comment]
Wow.  Thanks for the acknowledgment.   I have learned much from your project.
Best luck in your endeavors.
We will talk again.
