### ISSUE TITLE
Is there an online demo somewhere?

### ISSUE THREAD

**Issue by MarcGodard** [baianat/verte#7]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Abdelrahman3D** [comment]
You can check the online **docs** here: https://baianat.github.io/verte/

**Comment by MarcGodard** [comment]
Those are just docs... didn't see an easy to get too demo... but no big deal, I found one I like...

**Comment by Abdelrahman3D** [comment]
Sorry for inconvenient, but did you check the examples page in docs here: https://baianat.github.io/verte/examples.html ?

**Comment by Abdelrahman3D** [comment]
Sorry for inconviennt, here is a working [jsfiddle](https://jsfiddle.net/1n27aj8b/5/), for more examples please check the examples page on docs here: https://baianat.github.io/verte/examples.html.
